"""Mailbox domain ORM models.

MailboxProfile stores:
  - the user's upstream IMAP/SMTP configuration
  - upstream credentials encrypted at rest via Fernet
  - Mindwall-issued proxy credentials (username + bcrypt-hashed password)
  - connectivity status and last-check metadata

Enums use native_enum=False so they are stored as VARCHAR in both PostgreSQL
and SQLite, keeping migrations simple and portable.
"""

import enum
from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, Integer, String, Text
from sqlalchemy import Enum as SAEnum
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base


class ImapSecurity(enum.StrEnum):
    """TLS/security mode for upstream IMAP connections."""

    SSL_TLS = "ssl_tls"      # Connect with TLS from the start  (port 993)
    STARTTLS = "starttls"    # Plain connection upgraded via STARTTLS (port 143)
    NONE = "none"            # Unencrypted — not recommended, here for compatibility


class SmtpSecurity(enum.StrEnum):
    """TLS/security mode for upstream SMTP connections."""

    SSL_TLS = "ssl_tls"      # Connect with TLS from the start  (port 465)
    STARTTLS = "starttls"    # Plain connection upgraded via STARTTLS (port 587)
    NONE = "none"            # Unencrypted — not recommended


class MailboxStatus(enum.StrEnum):
    """Lifecycle / connectivity status of a MailboxProfile."""

    ACTIVE = "active"
    INACTIVE = "inactive"
    PENDING = "pending_verification"     # Registered but not yet tested
    CONNECTION_ERROR = "connection_error"


# Security mode labels for UI display
IMAP_SECURITY_LABELS: dict[str, str] = {
    ImapSecurity.SSL_TLS: "SSL/TLS (port 993)",
    ImapSecurity.STARTTLS: "STARTTLS (port 143)",
    ImapSecurity.NONE: "None — unencrypted",
}

SMTP_SECURITY_LABELS: dict[str, str] = {
    SmtpSecurity.SSL_TLS: "SSL/TLS (port 465)",
    SmtpSecurity.STARTTLS: "STARTTLS (port 587)",
    SmtpSecurity.NONE: "None — unencrypted",
}


class MailboxProfile(Base):
    """Upstream mailbox configuration registered by a Mindwall user.

    Upstream IMAP and SMTP passwords are stored encrypted at rest.
    Proxy credentials (proxy_username, proxy_password_hash) are the
    Mindwall-issued credentials that users put in their mail client.
    """

    __tablename__ = "mailbox_profiles"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    owner_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # Human-readable name and the email address this mailbox serves.
    display_name: Mapped[str] = mapped_column(String(255), nullable=False)
    email_address: Mapped[str] = mapped_column(String(255), nullable=False, index=True)

    # ------------------------------------------------------------------
    # Upstream IMAP configuration
    # ------------------------------------------------------------------
    imap_host: Mapped[str] = mapped_column(String(255), nullable=False)
    imap_port: Mapped[int] = mapped_column(Integer, nullable=False)
    imap_username: Mapped[str] = mapped_column(String(255), nullable=False)
    # Fernet-encrypted upstream IMAP password. Never decrypted outside the service layer.
    imap_password_enc: Mapped[str] = mapped_column(Text, nullable=False)
    imap_security: Mapped[ImapSecurity] = mapped_column(
        SAEnum(ImapSecurity, name="imap_security", native_enum=False, length=20),
        nullable=False,
        default=ImapSecurity.SSL_TLS,
    )

    # ------------------------------------------------------------------
    # Upstream SMTP configuration
    # ------------------------------------------------------------------
    smtp_host: Mapped[str] = mapped_column(String(255), nullable=False)
    smtp_port: Mapped[int] = mapped_column(Integer, nullable=False)
    smtp_username: Mapped[str] = mapped_column(String(255), nullable=False)
    # Fernet-encrypted upstream SMTP password. Never decrypted outside the service layer.
    smtp_password_enc: Mapped[str] = mapped_column(Text, nullable=False)
    smtp_security: Mapped[SmtpSecurity] = mapped_column(
        SAEnum(SmtpSecurity, name="smtp_security", native_enum=False, length=20),
        nullable=False,
        default=SmtpSecurity.STARTTLS,
    )

    # ------------------------------------------------------------------
    # Mailbox lifecycle status
    # ------------------------------------------------------------------
    status: Mapped[MailboxStatus] = mapped_column(
        SAEnum(MailboxStatus, name="mailbox_status", native_enum=False, length=30),
        nullable=False,
        default=MailboxStatus.PENDING,
    )

    # ------------------------------------------------------------------
    # Mindwall proxy credentials
    # These are generated by Mindwall and given to the user to configure
    # in their mail client. They never equal the upstream credentials.
    # ------------------------------------------------------------------
    # The proxy username is shown permanently (not a secret).
    proxy_username: Mapped[str | None] = mapped_column(
        String(100), unique=True, nullable=True
    )
    # bcrypt hash of the proxy password (one-way, cannot be recovered).
    # The plaintext password is shown once at creation/reset time via session flash.
    proxy_password_hash: Mapped[str | None] = mapped_column(String(255), nullable=True)

    # ------------------------------------------------------------------
    # Connectivity check results
    # ------------------------------------------------------------------
    last_connection_check_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    # Safe user-facing error message from the last failed connectivity test.
    last_connection_error: Mapped[str | None] = mapped_column(String(500), nullable=True)

    def __repr__(self) -> str:
        return (
            f"<MailboxProfile id={self.id} owner_id={self.owner_id} "
            f"email={self.email_address!r} status={self.status}>"
        )
